### ISSUE TITLE
Publish extension on PECL

### ISSUE THREAD

**Issue by mlocati** [zephir-lang/php-zephir-parser#104]
What about publishing this extension to PECL? I see we already have https://pecl.php.net/package/zephir_parser but there's no version published there...

**Comment by Jeckerson** [comment]
@AlexNDRmac Do we even need this package via pecl?

**Comment by mlocati** [comment]
It's much easier to install/update extensions via the pecl command...

**Comment by Jeckerson** [comment]
Now it is possible to install parser via `pecl install zephir_parser`.
