### ISSUE TITLE
Please provides tests in the pecl archive

### ISSUE THREAD

**Issue by remicollet** [zephir-lang/php-zephir-parser#127]
Using `role="test"`

Useful to allow downstream (packager) to run them

**Comment by Jeckerson** [comment]
Do we need to specify each file individually or there is wildcard for this?

**Comment by remicollet** [comment]
no wilcard, 1 line per file

**Comment by Jeckerson** [comment]
@remicollet Btw, is it possible to upload pecl package via CI?

**Comment by remicollet** [comment]
I don't think so (and don't think it makes sense)

**Comment by Jeckerson** [comment]
Why not. Perfect working example - publish deb/rpm packages from CI:

![image](https://user-images.githubusercontent.com/3289702/133890171-820079a1-c550-40fd-95c8-4d3477c4bb76.png)

Refs:
* https://github.com/phalcon/packagecloud
* https://packagecloud.io/phalcon
