### ISSUE TITLE
The Zephir Parser extension is outdated.

### ISSUE THREAD

**Issue by cline-pk** [zephir-lang/php-zephir-parser#133]
zephir and php-zephir-parser both files and up to dated with latest version on php7.2 but always getting error.
when i run command. > cd /root/xtreammasters && zephir build

// output error always.

           The Zephir Parser extension is outdated.
           Note: Zephir no longer distributed with internal parser.
           Minimum required Zephir Parser version: 1.3.0

           To install latest stable Zephir Parser please refer to:
           https://github.com/phalcon/php-zephir-parser

**Comment by joeluodongjiu** [comment]
v1.4.1

**Comment by Jeckerson** [comment]
@joeluodongjiu this is `Zephir Parser` version, not Zephir.

Use latest version of Zephir, check it here - https://github.com/zephir-lang/zephir/releases
