### ISSUE TITLE
php7.2 An error occurred

### ISSUE THREAD

**Issue by gaoruiqiang3003** [zephir-lang/php-zephir-parser#134]
The Zephir Parser extension is outdated.
           Note: Zephir no longer distributed with internal parser.
           Minimum required Zephir Parser version: 1.3.0

           To install latest stable Zephir Parser please refer to:
           https://github.com/phalcon/php-zephir-parser

**Comment by gaoruiqiang3003** [comment]
my Zephir Parser is 1.4.1

**Comment by Jeckerson** [comment]
@gaoruiqiang3003 Hello, please use Zephir `0.12.21` (https://github.com/zephir-lang/zephir/releases/tag/0.12.21) or below

For PHP >= 7.4 use `0.13.0` or above.

**Comment by zubin999** [comment]
I got the same problem on build,the php version is 7.2.34

> PHP 7.2.34 (cli) (built: Jun  7 2022 16:03:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v11.0.1, Copyright (c) 2002-2022, by ionCube Ltd.
zephir parser version is v1.5.3

zephir version is 0.12.1

>  _____              __    _
> /__  /  ___  ____  / /_  (_)____
>  / /  / _ \/ __ \/ __ \/ / ___/
> / /__/  __/ /_/ / / / / / /
> /____/\___/ .___/_/ /_/_/_/
>          /_/
> 
> Zephir 0.12.1 by Andres Gutierrez and Serghei Iakovlev (25cf1fd)
