### ISSUE TITLE
The Zephir Parser extension is outdated.

### ISSUE THREAD

**Issue by cline-pk** [zephir-lang/php-zephir-parser#140]
Hi, i'm getting this error even i'm using latest Zephir Parser extension 1.5.0
 
 [ERROR]

         ─────────────────────────────────────
         ───────────────────────
           The Zephir Parser extension is outdated.
           Note: Zephir no longer distributed with internal parser.
           Minimum required Zephir Parser version: 1.3.0

           To install latest stable Zephir Parser please refer to:
           https://github.com/phalcon/php-zephir-parser
         ─────────────────────────────────────
         ───────────────────────

**Comment by gaoruiqiang3003** [comment]
I have the same problem

**Comment by gaoruiqiang3003** [comment]
I have the same problem
