### ISSUE TITLE
Please add the TS version of the dll libraries

### ISSUE THREAD

**Issue by OSPanel** [zephir-lang/php-zephir-parser#145]
Please add the TS version of the dll libraries v1.5.2 for PHP 7.0-8.2.

Currently, only versions 1.4.1  (PHP 7.1-7.2), 1.4.2 (PHP 7.3) and 1.5.0 (PHP 7.4-8.1) are available for download in the PECL repository, and there are only NTS versions in Github.

**Comment by Jeckerson** [comment]
Added in `v1.5.3`
